// Winter Phase 9b (P9b-1/P9b-5/P9b-8) — the DATA behind the Norma→Winter codemod and the residue
// test. Nothing else in the repo decides what a rename is allowed to leave behind:
//
//   * `RENAME_ALLOWLIST` — literals the codemod PROTECTS (they are placeholdered around both passes)
//     and the residue test PERMITS afterwards. Every entry names external infrastructure the user
//     owns (a GitHub repo name, a Keychain credential profile, a live feed) — the repo does not get
//     to rename those by editing itself, so the rename leaves them and 9c/the user flip them.
//   * `EXPLICIT_TOKEN_MAP` — whole-token renames applied BEFORE the generic case-preserving pass,
//     for the identifiers where "Norma" meant "the host side of a host/runtime pair" (a blind
//     `norma→winter` there yields `WINTER_WINTER_…` / `winterToWinter…`) and for the two names that
//     would collide with the SDK's own exports (`WINTER_BRAND`, `WinterTaskStatus`).
//   * `TRAP_LOOKAHEAD` — the generic pass never touches `normal*` / `abnormal` / `normative`.
//
// Adding an entry here is a reviewed edit: the residue test fails on any `norma` the allowlist does
// not permit AND on any allowlist entry that no longer matches anything (no dead entries).

export interface AllowlistEntry {
  /** Stable id (used in reports). */
  id: string;
  /** The protected literal, as a regex source (case-sensitive unless the entry says otherwise). */
  regex: RegExp;
  /** Optional path globs (simple `**`/`*` only) — when present the entry only applies to those files. */
  files?: string[];
  /** Why the literal survives the rename and who flips it. */
  why: string;
}

/** The generic pass replaces `norma|Norma|NORMA` only when NOT followed by this lookahead. */
export const TRAP_LOOKAHEAD = "(?![lL]|tiv)";

/** Directories/files the CONTENT pass never rewrites (paths may still move). */
export const EXEMPT_PATHS: readonly string[] = [
  "scripts/rename/", // contains the rules themselves
  "releases/appcast.xml", // the LIVE norma Sparkle feed — frozen byte-for-byte (P9b-9)
  "bun.lock", // regenerated by `bun install`, never codemodded (P9b-3)
  "packages/core/src/legacy-names.ts", // P9b-6 — 9c's migrator input (does not exist at codemod time)
  "apple/Winter/Sources/App/LegacyNames.swift", // P9b-6 — the Swift twin
];

/** Extensions treated as binary: path rename only, content untouched. */
export const BINARY_EXTENSIONS: ReadonlySet<string> = new Set([
  "png", "jpg", "jpeg", "gif", "icns", "ico", "pdf", "zip", "gz", "tgz", "xz", "db", "sqlite", "sqlite3",
  "ttf", "otf", "woff", "woff2", "mp4", "mov", "wav", "aiff", "car", "xcframework", "a", "dylib", "so",
  "o", "bin", "dat", "heic", "webp", "svgz",
  // Office fixtures are zip/OLE binaries (their CONTENT is test data, never rewritten — P9b-29)
  "odt", "ods", "odp", "docx", "xlsx", "pptx", "xls", "doc", "ppt",
]);

/** The app-test files that read the binary Office fixtures (P9b-29); the only files the fixture-content entry covers. */
const FILES_OFFICE_FIXTURE_TESTS = [
  "apple/Winter/Tests/WinterAppTests/OfficeDocsCommandTests.swift",
  "apple/Winter/Tests/WinterAppTests/OfficeSheetsCommandTests.swift",
  "apple/Winter/Tests/WinterAppTests/OfficeSlidesCommandTests.swift",
  "apple/Winter/Tests/WinterAppTests/OfficeHelperLiveTests.swift",
  "apple/Winter/Tests/WinterAppTests/OfficeRuntimeLiveTests.swift",
  "apple/Winter/Tests/WinterAppTests/OfficePlaceAtomicallyTests.swift",
];

export const RENAME_ALLOWLIST: readonly AllowlistEntry[] = [
  {
    id: "gh-repo",
    // The PRE-9c repo path `yanlingLabs/norma`. The GitHub repo was renamed to `yanlingLabs/winter`
    // in Phase 9c (P9c-6) and every live reference flipped; GitHub redirects the old path, so ONLY
    // the byte-frozen legacy feed (its historical enclosure URLs) and the codemod's own tests may
    // still spell it. NOT `yanlingLabs/norma-ios` (own entry) and not a longer name.
    regex: /yanlingLabs\/norma(?![A-Za-z0-9_-])/g,
    files: ["releases/appcast.xml", "scripts/rename/codemod.test.ts"],
    why: "the pre-rename GitHub repo path, kept only in the frozen legacy feed's historical enclosure URLs (redirected by GitHub) and the codemod's tests (P9c-6)",
  },
  {
    id: "ios-repo",
    // The iOS sibling's LOCAL CHECKOUT name (`../norma-ios`, `norma-ios/project.yml`, bare `norma-ios`
    // in prose). Its GitHub repo is `yanlingLabs/winter-ios` since Phase 9c (P9c-6); the checkout
    // directory keeps its name until the user renames it. The iOS app's OWN bundle id
    // `com.yanlinglabs.norma-ios` is preceded by a dot, so it is NOT protected and renamed to
    // `com.yanlinglabs.winter-ios` (P9b-11).
    regex: /(?<![A-Za-z0-9_.])norma-ios(?![A-Za-z0-9_])/g,
    why: "the iOS sibling's local checkout directory name — user-owned directory rename (the repo itself is `winter-ios` since 9c)",
  },
  {
    id: "infra-keychain",
    regex: /com\.norma\.(infra|cf)(?![A-Za-z0-9_.-])/g,
    why: "the user's live relay-ops credentials in the login Keychain (infra/relay/README.md) — renaming the service string strands the items",
  },
  {
    id: "crypto-domain-tags",
    // Versioned Ed25519/HKDF domain-separation tags: `norma-relay-config/1` is baked into the two
    // checked-in SIGNED relay configs (and a pinned cross-language test vector); `norma-pair-proof/1`
    // and `norma-pair-sas/1` are computed live by BOTH pairing parties. They are protocol constants
    // (Global Constraints: no protocol change) — a rename would invalidate the signed artifacts and
    // break pairing between a Winter Mac and a Norma phone across the 9c cutover. They change only
    // by a deliberate `/2` bump with a re-sign/re-pair plan (P9b-28).
    regex: /norma-(relay-config|pair-proof|pair-sas)\/[0-9]+/g,
    why: "versioned crypto domain-separation tags — protocol constants baked into signed artifacts and live pairing; bump deliberately, never rename",
  },
  {
    id: "config-key-keychain",
    regex: /com\.norma\.config-key(?![A-Za-z0-9_.-])/g,
    why: "the login-Keychain service holding the relay-config SIGNING key — same class as com.norma.infra/cf (P9b-28)",
  },
  {
    id: "infra-ssh-key",
    regex: /norma-relay(?![A-Za-z0-9_])/g,
    files: ["infra/**"],
    why: "the dedicated relay SSH keypair `~/.ssh/norma-relay` and the live relay resource names — user-owned infrastructure",
  },
  {
    id: "notary-profile",
    regex: /norma-notary(?![A-Za-z0-9_-])/g,
    why: "a notarytool credential profile stored on this machine — renaming it makes release preflight fail until the user re-stores credentials",
  },
  {
    id: "identity-guard",
    regex: /norma-private(?![A-Za-z0-9_-])/g,
    why: "the local-only identity guard's directory (`~/norma-private/git-hooks`) — user-owned, never in the repo",
  },
  {
    id: "checkout-dir",
    regex: /Norma v2(?![A-Za-z0-9_])/g,
    why: "the on-disk checkout directory name — user-owned (it is also the Claude Code project key)",
  },
  {
    id: "rename-tooling",
    regex: /norma|Norma|NORMA/g,
    files: ["scripts/rename/**", "packages/core/test/rename/**"],
    why: "the codemod, its tests and the residue test spell the old name on purpose",
  },
  {
    id: "frozen-norma-feed",
    regex: /norma|Norma|NORMA/g,
    files: ["releases/appcast.xml"],
    why: "the live Sparkle feed for shipped Norma installs — it holds 9c's terminal handoff entry (0.2.015, the copy of norma-final's item per P9c-13) and is frozen again from here on (WS-16 §19)",
  },
  {
    id: "claude-md-legacy-trap",
    // CLAUDE.md's LEGACY TRAP paragraph (P9b-13) must SPELL the stale wrapper and env names so a
    // reader recognises them on their own machine.
    // …and the Hard-rules line that keeps protecting the user's LIVE pre-migration install
    // (`Norma.app` / `com.norma.app` / `~/.norma` / `com.norma.core`) until Migration B (9c).
    // …and (9c) the Migration B section, which names the legacy project files a `winter migrate-project` converts.
    regex: /norma-dev|NORMA_HOME|NORMA_PROFILE|\.norma-dev|Norma\.app|com\.norma\.(app|core)|~\/\.norma(?![A-Za-z0-9_-])|NORMA\.md|(?<![A-Za-z0-9_~/])\.norma(?=\/)/g,
    files: ["CLAUDE.md"],
    why: "the dev-guide trap naming the stale `norma-dev` wrapper/env names, and the hard rule naming the live Norma install until 9c (P9b-13; whole-branch review)",
  },
  {
    id: "office-fixture-content",
    // Test DATA, not a product surface (P9b-29): the Office fixtures under Tests/…/Fixtures/office are
    // binary documents whose paragraphs/slide titles say NORMA GATE / NORMA PAGE TWO / Norma T6 Slide
    // One|Two|Three; the tests that read, type into, save and re-open them assert those bytes (and a
    // case-insensitive `find: "norma"` against them). The expectations mirror the fixtures verbatim.
    regex: /NORMA(?![A-Za-z])( INC)*( GATE(WAY)?| PAGE TWO)?|Norma T6 Slide|"norma"/g, // bare NORMA + "NORMA INC…" = the replace drill's find/replaceWith/asserted results
    // Scoped to the files that read the fixtures (whole-branch review): a leak elsewhere in the app tests still fails.
    files: FILES_OFFICE_FIXTURE_TESTS,
    why: "expectations that mirror binary Office fixture content byte-for-byte (P9b-29)",
  },
  {
    id: "legacy-names",
    regex: /norma|Norma|NORMA/g,
    files: ["packages/core/src/legacy-names.ts", "apple/Winter/Sources/App/LegacyNames.swift"],
    why: "P9b-6 — the one module per language that spells the OLD names for 9c's migrator and the two legacy launchd/wrapper teardowns",
  },
  {
    id: "deprecated-norma-cask",
    // Phase 9c (P9c-5): the tap keeps a `norma` cask marked deprecate! with replacement_cask "winter" —
    // its template, and the publisher that PUTs `Casks/norma.rb`, must spell the old cask name.
    regex: /norma|Norma/g,
    files: ["packaging/norma-deprecated.rb", "scripts/publish-tap.ts", "scripts/publish-tap.test.ts"],
    why: "the deprecated `norma` Homebrew cask (P9c-5) — user-facing continuity for existing brew installs; the winter cask replaces it",
  },
  {
    id: "migration-user-docs",
    // Phase 9c: the user-facing migration story ("Coming from Norma?", the 0.111.0 release notes) has to
    // name the product users are coming from, its home directory and its cask. Prose only — never code.
    regex: /norma|Norma|NORMA/g,
    files: ["README.md", "releases/notes/*.md"],
    why: "user-facing migration documentation (Phase 9c) must name Norma, ~/.norma and the norma cask so users recognise what is being migrated",
  },
  {
    id: "old-scheme-comments",
    // Phase 9c (P9c-2): the version code explains what the pre-rename `#.#.###` scheme was and that
    // `norma-final` keeps its own copy of the old regex — comments only, next to the new FORMAT.
    regex: /Norma(?= #\.#\.###| scheme| is now Winter)|Norma's `#\.#\.###`|norma-final/g,
    files: ["scripts/version-lib.ts", "scripts/release.ts", "packages/core/test/version-consistency.test.ts"],
    why: "comments contrasting the new #.###.# scheme with the pre-rename one and naming the norma-final branch (P9c-2)",
  },
];

/**
 * Whole-token renames applied BEFORE the generic pass (P9b-8). Keys are matched with
 * identifier boundaries (`[A-Za-z0-9_]` on either side is a non-match); the two dotted/hyphenated
 * values carry their own boundary classes in `codemod.ts`.
 */
export const EXPLICIT_TOKEN_MAP: readonly (readonly [from: string, to: string])[] = [
  ["NORMA_BRAND", "CORE_BRAND"],
  ["buildNormaBrand", "buildCoreBrand"],
  ["NormaTaskStatus", "HostTaskStatus"],
  ["normaId", "hostId"],
  ["normaToolNameFor", "hostToolNameFor"],
  ["normaToolName", "hostToolName"],
  ["WINTER_NORMA_TOOL_PAIRS", "RUNTIME_HOST_TOOL_PAIRS"],
  ["WINTER_TO_NORMA", "RUNTIME_TO_HOST"],
  ["NORMA_TO_WINTER", "HOST_TO_RUNTIME"],
  ["winterToNormaRoutineId", "runtimeToHostRoutineId"],
  ["NORMA_WINTER_EXECUTABLE", "WINTER_RUNTIME_EXECUTABLE"],
  ["NORMA_WINTER_REQUIRE_BINARY", "WINTER_RUNTIME_REQUIRE_BINARY"],
  ["NORMA_WINTER_SDK_CHECKOUT", "WINTER_SDK_CHECKOUT"],
  ["NORMA_WINTER_SIGN_IDENTITY", "WINTER_RUNTIME_SIGN_IDENTITY"],
  ["NORMA_STAGE_WINTER_PATH", "WINTER_STAGE_RUNTIME_PATH"],
  ["norma-winter", "winter"], // the brand's processLabel value
  ["com.norma.winter", "com.winter.runtime"], // the `winter` re-sign identifier (P8d-14 → P9b-8)
];

/** Post-pass gate: none of these may survive anywhere outside `scripts/rename/`. */
export const DOUBLE_WINTER = /winter[-_]?winter|WinterWinter|winterWinter|WINTER[-_]?WINTER/g;
