#!/usr/bin/env bun
// ComputerV2 Phase 2 — bundles the browser engine's PAGE RUNTIME (`packages/core/src/computer-use/browser/page-runtime/
// main.ts`) for the browser (IIFE, no minify) into the COMMITTED `bundle.generated.ts` (`PAGE_RUNTIME_SOURCE`), the
// string the engine evaluates in each frame's isolated "winter" world. Committed, never built at runtime: dev and the
// compiled daemon run the same bytes, with no file reads. A unit test fails when the committed bundle is stale.
//
//   bun run build:page-runtime            write bundle.generated.ts
//   bun run build:page-runtime --check    exit 1 when the committed file differs from a fresh build
import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const DIR = join(import.meta.dir, "..", "packages", "core", "src", "computer-use", "browser", "page-runtime");
const ENTRY = join(DIR, "main.ts");
const OUT = join(DIR, "bundle.generated.ts");

/** The generated module's text for a fresh build (the same function the stale-bundle test calls). */
export async function renderPageRuntimeModule(): Promise<string> {
  const built = await Bun.build({ entrypoints: [ENTRY], root: DIR, target: "browser", format: "iife", minify: false, sourcemap: "none" });
  if (!built.success) throw new Error(`page runtime build failed:\n${built.logs.map((l) => String(l)).join("\n")}`);
  // Bun names each bundled module with a path relative to the CWD: kept to its file name, so the bytes do not depend
  // on where the build ran (the stale-bundle test runs from the package, the script from the repo root).
  const js = (await built.outputs[0]!.text()).trim().replace(/^(\s*)\/\/ [^\n]*page-runtime\/([^/\n]+\.ts)$/gm, "$1// $2");
  return [
    "// GENERATED by scripts/build-page-runtime.ts from ./main.ts — do not edit; run `bun run build:page-runtime`.",
    "// The browser engine evaluates this in each frame's isolated \"winter\" world (never the page's own).",
    "/* eslint-disable */",
    `export const PAGE_RUNTIME_SOURCE: string = ${JSON.stringify(js)};`,
    "",
  ].join("\n");
}

if (import.meta.main) {
  const next = await renderPageRuntimeModule();
  if (process.argv.includes("--check")) {
    let current = "";
    try { current = readFileSync(OUT, "utf8"); } catch { /* absent */ }
    if (current !== next) {
      console.error("bundle.generated.ts is stale — run `bun run build:page-runtime`");
      process.exit(1);
    }
    console.log("bundle.generated.ts is up to date");
  } else {
    writeFileSync(OUT, next);
    console.log(`wrote ${OUT} (${next.length} bytes)`);
  }
}
