import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

export const ROOT = join(import.meta.dir, "..");
export const FORMAT = /^(\d+)\.(\d+)\.(\d{3})$/;

export function readCanonical(): string {
  const v = readFileSync(join(ROOT, "VERSION"), "utf8").trim();
  if (!FORMAT.test(v)) throw new Error(`VERSION "${v}" does not match #.#.### (e.g. 0.2.001)`);
  return v;
}

/** 0.2.001 -> 0.2.1 — semver forbids leading zeros; used ONLY for the private package.jsons. */
export function semverTwin(v: string): string {
  const m = v.match(FORMAT);
  if (!m) throw new Error(`not a canonical version: ${v}`);
  return `${Number(m[1])}.${Number(m[2])}.${Number(m[3])}`;
}

const PKGS = ["cli", "core", "protocol", "plugin-sdk"];

/** Stamp the canonical version into every source. Returns the files written. */
export function stampAll(v: string): string[] {
  const twin = semverTwin(v);
  const files: string[] = [];
  const put = (path: string, content: string) => {
    writeFileSync(path, content);
    files.push(path);
  };

  // 1. Generated TS constant (canonical) — the daemon banner/handshake source.
  put(
    join(ROOT, "packages", "core", "src", "version.ts"),
    `// GENERATED by scripts/sync-version.ts from /VERSION — do not edit by hand.\nexport const CORE_VERSION = "${v}";\n`,
  );

  // 2. package.jsons — semver-normalized twin (private packages, never published).
  for (const p of PKGS) {
    const path = join(ROOT, "packages", p, "package.json");
    const pkg = JSON.parse(readFileSync(path, "utf8")) as Record<string, unknown>;
    pkg.version = twin;
    put(path, JSON.stringify(pkg, null, 2) + "\n");
  }

  // 3. apple: project.yml is the XcodeGen source of truth; Support/Info.plist is the
  //    git-tracked generated mirror that builds actually read (INFOPLIST_FILE) until the
  //    next `xcodegen generate`. Stamp BOTH so a sync never needs xcodegen installed.
  const yml = join(ROOT, "apple", "Winter", "project.yml");
  put(
    yml,
    readFileSync(yml, "utf8")
      .replace(/CFBundleShortVersionString: "[^"]*"/, `CFBundleShortVersionString: "${v}"`)
      .replace(/CFBundleVersion: "[^"]*"/, `CFBundleVersion: "${v}"`),
  );
  const plist = join(ROOT, "apple", "Winter", "Support", "Info.plist");
  put(
    plist,
    readFileSync(plist, "utf8")
      .replace(
        /(<key>CFBundleShortVersionString<\/key>\s*<string>)[^<]*(<\/string>)/,
        `$1${v}$2`,
      )
      .replace(/(<key>CFBundleVersion<\/key>\s*<string>)[^<]*(<\/string>)/, `$1${v}$2`),
  );
  return files;
}
